### ISSUE TITLE
Artwork disappeared from upcoming battle queue

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#15]
I had uploaded this artwork to the battle queue and voted for it once. Then it disappeared. 

`_DALL·E 2024-02-19 18.59.12 - Picture Nearchan in an enchanting anime-style scene, where she's playfully tipping her coffee cup at the edge of a futuristic table filled with advanc`

`_DALL·E 2024-02-19 18.59.12 - Picture Nearchan in an enchanting anime-style scene, where she's playfully tipping her coffee cup at the edge of a futuristic table filled with advanc_grayscale`

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/6473f5db-f6ed-4169-99b5-c66e40666991)

**Comment by SathishTeckas** [comment]
This issue was solved in api desgin.
[link](https://github.com/Teckas-Technologies/daily-art-battle/blob/eb316e2890b2c6dc4323d217eca643b434040b97/pages/api/mintNfts.ts#L10)
