### ISSUE TITLE
add introduction text so new users understand what the site is about

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#16]
# Introduction Explainer (above the current battle images)

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/d6136144-2a8f-46a9-8437-98bbcafb6311)

`Welcome to GFXvs, where creators compete with their masterpieces and you vote to win exclusive NFT rewards! Each day, two pieces of art face off, and you decide the winner by casting your vote. For each artwork, one lucky voter is awarded a 1:1 NFT, while everyone else receives participation reward editions. Join the battle by connecting your NEAR wallet, vote for your favorite art, and earn exclusive NFT rewards!`

# Upcoming Arts Explainer (under the Upcoming Arts h2)

`Upvote your favorite artworks to influence what will be up for battle next. Think you’ve got what it takes? Upload your own masterpiece and join the competition!`

# Previous Battles Explainer (under the Previous Battles h2)
`[Check your wallet](https://wallet.mintbase.xyz/) to see your rewards and the spoils of victory if you were a lucky winner. Relive the excitement and see which masterpieces emerged victorious!`

**Comment by SathishTeckas** [comment]
This issue was solved by adding intro texts.
![Uploading Screenshot 2024-06-11 213638.png…]()

**Comment by starpause** [comment]
Text under "Upcoming Arts" is missing on https://[testnet-daily-art-battle.vercel.app](https://testnet-daily-art-battle.vercel.app/)/

**Comment by starpause** [comment]
Can we make this helper/explainer text smaller and italic? That way it isn't distracting from the more important page elements that users need to interact with. Example is using .8rem

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/7df55851-b7d9-4a7b-88c8-e7ac5d8505b9)
