### ISSUE TITLE
page doesn't refresh or show new content when the timer runs down

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#17]
As a user I was watching the timer countdown the seconds. When it finally ended the timer disappeared but nothing else happened. I expected something to happen, like the artwork switching to the new art and the timer resetting.

**Comment by SathishTeckas** [comment]
The issue was solved changing the api logic.
[link](https://github.com/Teckas-Technologies/daily-art-battle/blob/eb316e2890b2c6dc4323d217eca643b434040b97/pages/api/mintNfts.ts#L10)
