### ISSUE TITLE
After choosing an artwork there isn't any indicator of what I picked

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#2]
Current behavior is no indicator of which artwork I picked.

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/5de9baab-3b7d-46cb-905d-937165139f6b)

As a user I want to know or remember which artwork I chose.

I also expect the buttons to have a visually different "disabled" state so it's obvious I've voted and can't push the buttons again.

**Comment by SathishTeckas** [comment]
This issue solved by adding colour difference to the button after voting.
[Code](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/src/components/ArtPiece.tsx#L17)
