### ISSUE TITLE
P5 . Upcoming Battle Pagination - 2nd page is blank/empty

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#23]
It's possible to hit "Next" on the Upcoming Battle Pagination, but no content is shown.

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/bb2db587-6620-43e3-aae0-10e093404371)

**Comment by starpause** [comment]
I'm still able to reproduce this after uploading 10 artworks to https://testnet-daily-art-battle.vercel.app/

**Comment by SathishTeckas** [comment]
Position changing issue in upcoming battles

**Comment by Immanuel-john** [comment]
> Position changing issue in upcoming battles

to add more on it. once i click on next page the page takes to me to previous battles table.
