### ISSUE TITLE
User should receive only one copy of the derivative artwork

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#24]
For this battle, a user received multiple copies of the derivative artwork. They should receive only 1.

https://www.mintbase.xyz/meta/gfxvseditions.mintbase1.near%3A058fb992fbeadfe0f15d4dc0bbbc7682

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/4faff1cd-2a58-43a2-8d98-432861b224e1)

**Comment by SathishTeckas** [comment]
This issue was solved by changing the api.
[link](https://github.com/Teckas-Technologies/daily-art-battle/blob/eb316e2890b2c6dc4323d217eca643b434040b97/pages/api/mintNfts.ts#L10)
