### ISSUE TITLE
Timer set higher than 24h

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#29]
![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/cb3692d2-b3db-4a90-a8f1-134dc4f67faf)

**Comment by SathishTeckas** [comment]
This issue was solved by changing the create battle logic.
[link](https://github.com/Teckas-Technologies/daily-art-battle/blob/eb316e2890b2c6dc4323d217eca643b434040b97/utils/battleSelection.ts#L25)
