### ISSUE TITLE
Not able to vote on Upcoming Arts

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#3]
When I try to vote for an Upcoming Art I get an error message. I get this error message before and after I vote for the current artwork. Eventually we want to give users points for voting and for submitting artwork, but for now can we allow user to make one upvote a day?

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/6114e410-dc0b-4afb-9225-3a52b731e4c3)

**Comment by SathishTeckas** [comment]
This issue is solved by changing this api code.
[code](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/pages/api/artVote.ts#L12)
