### ISSUE TITLE
Logo for Favicon and Header 

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#31]
replace favicon and "daily art battle" in the header with this logo

![square crop _gfxvs logo metal style DALL·E](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/03923ed5-fbc0-44dc-8dfc-84bdf5c9ced8)

**Comment by starpause** [comment]
Don't need GFXvs text in the header, just logo. Here is a transparent version for the header, so that the backgrond color matches the header.

![square-gfxvs-logo-transparent](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/8b113517-d2fa-4cf7-833f-fc51cb7d8072)

**Comment by SathishTeckas** [comment]
This issue was solved by changing the ui.
[link](https://github.com/Teckas-Technologies/daily-art-battle/blob/eb316e2890b2c6dc4323d217eca643b434040b97/src/components/NearWalletConnector.tsx#L4)
