### ISSUE TITLE
Upload succeeds even if a unique rare isn't provided

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#36]
If an artist leaves "unique rare" empty the upload button can still be clicked. An error message is given, but then another dialog appears which says everything went fine, and the upload modal goes away (see below).

Instead, we should disable the upload button until an artist had uploaded both artworks and filled in a title. If there is an error with one of the fields, that field should get an indicator that shows it has a problem. 

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/4019ac8e-e537-4e87-90db-9d27e9eeabfd)

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/6da6e3b5-4482-4f7c-8d80-093481d8fa43)

**Comment by SathishTeckas** [comment]
The issue was solved by adding additional checks and by updating the code.
[code](https://github.com/Teckas-Technologies/daily-art-battle/blob/eb316e2890b2c6dc4323d217eca643b434040b97/src/components/ArtworkUploadForm.tsx#L14)
