### ISSUE TITLE
Battle component disappeared after i voted for upcoming arts

### ISSUE THREAD

**Issue by Immanuel-john** [Teckas-Technologies/daily-art-battle#42]
<img width="1512" alt="Screenshot 2024-06-12 at 4 25 47 PM" src="https://github.com/Teckas-Technologies/daily-art-battle/assets/20478067/7d098fce-e07c-4755-a877-f27105219c4c">

**Comment by Immanuel-john** [comment]
<img width="1512" alt="Screenshot 2024-06-12 at 4 25 47 PM" src="https://github.com/Teckas-Technologies/daily-art-battle/assets/20478067/7d098fce-e07c-4755-a877-f27105219c4c">

**Comment by SathishTeckas** [comment]
This issue was resolved by changing this code.
[code](https://github.com/Teckas-Technologies/daily-art-battle/blob/4ca219eaa00f41100df38da20e407ed7d056fc09/pages/api/battle.ts#L5)
