### ISSUE TITLE
Move timer to a heading

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#44]
Right now we don't have a heading at the top of the page. Let's move just the timer to the top of the page using h2 style. 

If possible, format it so it's just the countdown numbers and include MS so there's a sense of urgency/excitement.

HH:MM:SS:MS

While we are at it, let's increase the font size for h2. Maybe `.text-xl` to 2rem or so?

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/2306f52e-37ce-4ef9-99fe-95e999f04a23)

**Comment by starpause** [comment]
Because the timer text is only updating once a second it looks bad to have the MS up. Let's remove MS.

Because the numbers are decreasing it's obvious it's a countdown timer and we don't need the "time remaining" label. Let's remove "time remaining"

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/bd1af4b4-df6b-4283-b4a0-0712061e1dde)

Shorter, clearer paragraph text:

"Welcome to GFXvs, where creators clash for daily cash prizes. Cast your vote to secure participation NFTs and a chance to win an exclusive 1:1 masterpiece. Connect your NEAR wallet to join the thrilling competition!"

All H2: make 2rem across breakpoints (headers still appear too small so the sections aren't distinct enough).

**Comment by SathishTeckas** [comment]
This issue was resolved by changing in this code.
[Code](https://github.com/Teckas-Technologies/daily-art-battle/blob/2a6f1d73fc27fa20f10baffb231c76e06d7cb039/src/components/ArtBattle.tsx#L15)
