### ISSUE TITLE
P1 . Grid layout for Upcoming Arts

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#47]
Right now the Upcoming Arts is a table

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/64f17afc-9d7d-498d-872f-ce98eaa3be7d)

Could we instead have it be a grid? Clicking the up arrow icon will submit the vote and change the arrow from blue or black to green. 

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/c9ccd272-e7d5-4bac-bd11-f06158bc279f)

**Comment by starpause** [comment]
Can the grid be 3 images wide in every breakpoint? Inspired by instagram 3-wide grid which looks good even on mobile 

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/45fa3925-343c-4754-8826-aa82332c6cf0)

**Comment by starpause** [comment]
Can the art cover the whole div of the grid item? Instead of being an element of the grid item? Something like 

```
background-position: center;
background-size: cover;
```

Do not display the <p> such as "fafw by solo-litha.testnet", instead it can be the alt text for the image (or not present at all).

Ideally the upvote button is an icon so it takes up less space + it changes color when the user has already upvoted an artwork. 

<img width="362" alt="image" src="https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/394b9faa-a1c4-4d52-b5c1-7218dbc435cc">

**Comment by SathishTeckas** [comment]
less is more... it would look cleaner if we put the upvote button and upvote count directly on the image. that way we don't need a border.

**Comment by SathishTeckas** [comment]
can we color the vote button green after someone has clicked on it? that way they don't get this message so much

**Comment by SathishTeckas** [comment]
what is the icon next to the vote count? it would be cleaner if we have an up arrow icon rather than "vote" word, and the alt text for the icon can be "upvote"

then the count can be next to the upvote icon, we don't need the icon which i can not decipher

**Comment by SathishTeckas** [comment]
Can we have clicking on the rares image go to a tradeport link? Tradeport is good because they allow users to put in bids. For example

https://www.tradeport.xyz/near/collection/gfxvsrares.mintbase1.near?bottomTab=trades&tab=items&tokenId=0

**Comment by SathishTeckas** [comment]
the green button should not have a hover state, since it can not be clicked

the blue button should have a hover state, since it can be clicked
