### ISSUE TITLE
Display Artwork Title and Artist Name

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#6]
Under the artwork display "Art Title by user.near" in these places:
- Current Battle
- Upcoming Arts (don't need Artist Name in a separate column)
- Previous Battles

This can be in regular paragraph size.

**Comment by SathishTeckas** [comment]
This issue also solved by adding the art title and artist id 
[current battle](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/src/components/ArtPiece.tsx#L17)
[previous battle](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/src/components/PreviousBattlesTable.tsx#L6)
[upcoming battles](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/src/components/UpcomingBattlesTable.tsx#L6)
