### ISSUE TITLE
Previous Battles table update

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#7]
Update the Previous Battles table to have one Art in each. The columns can be

Unique Rare | Derivative Editions | Holders

That way both the Unique and Derivative art is visible. 

Holders will have this text:

```
Unique Rare Holder:
name.near

# fans holding Derivative Editions.
```

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/d26e7db5-94ea-4d9a-a1d1-823dc6b0af67)

**Comment by SathishTeckas** [comment]
This issue is solved by altering the table design in this code
[code](https://github.com/Teckas-Technologies/daily-art-battle/blob/19493ec43d84c579a5ee86e9253b211e5cf3002b/src/components/PreviousBattlesTable.tsx#L6)

**Comment by starpause** [comment]
@SathishTeckas is it possible to include some text that says how many derivative editions were minted in italics under the name of the unique rare holder?

```
uzur.testnet

# derivative edition holders
```

And update the `Holders` header to say `Unique Rare Owner`

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/f0eaf0b3-a7a5-4baa-b7d7-870a461565e1)

**Comment by starpause** [comment]
Display the looser as well as the winner of the battle
