### ISSUE TITLE
Error Loading Arts

### ISSUE THREAD

**Issue by starpause** [Teckas-Technologies/daily-art-battle#9]
![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/5d4b864e-9b6a-40c3-acbe-d393846a8427)

**Comment by starpause** [comment]
Similar error: after voting on gfxvs.com the images I can vote for disappeared and I have the "Error loading battles: Error loading arts" message

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/3cf61997-df39-4a88-8178-c1b18e78ad77)

**Comment by starpause** [comment]
Also maybe related, after upvoting for the upcoming battles, the site wasn't able to load todays battle data and the battle disappeared

![image](https://github.com/Teckas-Technologies/daily-art-battle/assets/408953/25ac2030-43e0-4c74-8e28-cd21b9b792d9)

**Comment by SathishTeckas** [comment]
This issue was solved by updating state props.
[link](https://github.com/Teckas-Technologies/daily-art-battle/blob/970b6d31437f349ceea635a83b3295a61ccf32c6/src/components/ArtBattle.tsx#L16)
